version: '3.9'
services:
  web:
    container_name: news-web
    build:
      context: .docker
    ports:
      - "8000:8000"
    volumes:
      - ./web:/var/www/web
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - DATABASE_URL=mysql://root:root@news-database:3306/news
    depends_on:
      - database
    tty: true

  database:
    image: mysql:8.4
    container_name: news-database
    ports:
      - 3306
    expose:
      - 3306
    volumes:
      - database:/var/lib/mysql
      #- ./docker/data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=news

  redis:
    image: redis:7.2-alpine3.19
    container_name: news-redis
    expose:
      - 6379

  elasticsearch:
    image: elasticsearch:8.13.4
    container_name: news-search
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elastic:/usr/share/elasticsearch/data
    expose:
      - 9200

volumes:
  database:
    driver: local
  vendor:
    driver: local
  elastic:
    driver: local

networks:
  default:
    name: moukail
